---
# This file configures https://pre-commit.com/
# Based on pre-commit hooks in
#   https://github.com/pre-commit/pre-commit-hooks
#   https://github.com/jumanjihouse/pre-commit-hooks
# to use specific hooks and options.
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.output
      - id: end-of-file-fixer
        exclude: \.(cp?p?$|output)
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: d5f40fa0553aa4bba71fcd73cf42933ae14d5116  # 9.0.0b5
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit
    rev: 9767b6c8211a6bf683875a0afcf2b390457a4b66  # v4.6.2
    hooks:
    -   id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # v3.21.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
    hooks:
      - id: black
        args: ["-l", "120"]
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: pytest -v -xxx
        description: Tests expected output of all scripts
        language: python
        types: [python]
        additional_dependencies: ["."]
